[tool.poetry]
name = "langgraph-checkpoint-mysql"
version = "2.0.11"
description = "Library with a MySQL implementation of LangGraph checkpoint saver."
authors = ["Theodore Ni <dev@ted.bio>"]
license = "MIT"
readme = "README.md"
repository = "https://www.github.com/tjni/langgraph-checkpoint-mysql"
packages = [{ include = "langgraph" }]

[tool.poetry.dependencies]
python = "^3.9.0,<4.0"
langgraph-checkpoint = "==2.0.9"
orjson = ">=3.10.1"
pymysql =  { version = "^1.1.1", optional = true }
aiomysql = { version = "^0.2.0", optional = true }
typing-extensions = "^4.12.2"

[tool.poetry.extras]
pymysql = ["pymysql"]
aiomysql = ["aiomysql"]

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.2"
codespell = "^2.2.0"
pytest = "^7.2.1"
anyio = "^4.4.0"
pytest-asyncio = "^0.21.1"
pytest-mock = "^3.11.1"
pytest-watch = "^4.2.0"
mypy = "^1.10.0"
pymysql = "^1.1.1"
aiomysql = "^0.2.0"
types-PyMySQL = "^1.1.0"
langgraph = "0.2.62"
syrupy = "^4.0.2"
pytest-repeat = "^0.9.3"
pytest-xdist = {extras = ["psutil"], version = "^3.6.1"}
sqlalchemy = "^2.0.36"

[tool.pytest.ini_options]
# --strict-markers will raise errors on unknown marks.
# https://docs.pytest.org/en/7.1.x/how-to/mark.html#raising-errors-on-unknown-marks
#
# https://docs.pytest.org/en/7.1.x/reference/reference.html
# --strict-config       any warnings encountered while parsing the `pytest`
#                       section of the configuration file raise errors.
addopts = "--strict-markers --strict-config --durations=5 -vv"
asyncio_mode = "auto"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.select = [
  "E",  # pycodestyle
  "F",  # Pyflakes
  "UP", # pyupgrade
  "B",  # flake8-bugbear
  "I",  # isort
]
lint.ignore = ["E501", "B008", "UP007", "UP006"]
exclude = [
  "langgraph-tests"
]

[tool.mypy]
# https://mypy.readthedocs.io/en/stable/config_file.html
disallow_untyped_defs = "True"
explicit_package_bases = "True"
warn_no_return = "False"
warn_unused_ignores = "True"
warn_redundant_casts = "True"
allow_redefinition = "True"
disable_error_code = "typeddict-item, return-value"
exclude = [
  "langgraph-tests"
]
