name: test

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database:
          - db: "mysql"
            version: "9"
          - db: "mysql"
            version: "8"
          - db: "mysql"
            version: "8.0.19"
          - db: "mariadb"
            version: "11"
          - db: "mariadb"
            version: "10"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    name: "test python ${{ matrix.python-version }} | ${{ matrix.database.db }} ${{ matrix.database.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-suffix: test-${{ inputs.working-directory }}

      - name: Install dependencies
        shell: bash
        run: uv sync --frozen --group dev

      - name: Run MySQL tests
        if: ${{ matrix.database.db == 'mysql' }}
        shell: bash
        env:
          MYSQL_VERSIONS: ${{ matrix.database.version }}
        run: make test

      - name: Run MariaDB tests
        if: ${{ matrix.database.db == 'mariadb' }}
        shell: bash
        env:
          MARIADB_VERSIONS: ${{ matrix.database.version }}
        run: |
          make test-mariadb

      - name: Ensure the tests did not create any additional files
        shell: bash
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
